# Squatchware keys for /boot/limine.conf, written by install-bootloader.sh.
interface_branding: SQUATCHWARE
interface_branding_color: d4a832
interface_help_color: ab9e7b
interface_help_color_bright: e9c45a
wallpaper: boot():/squatchware-boot.png
wallpaper_style: stretched
backdrop: 0f1a14
term_background: 60060c09
term_background_bright: 183826
term_foreground: f4e4bc
term_foreground_bright: fff8dc
term_palette: 060c09;db6250;6fae5a;d4a832;5b8fb9;a87ac8;3aa597;f4e4bc
term_palette_bright: ab9e7b;e8826f;8fcb78;e9c45a;7faed4;c49be0;5cc4b5;fff8dc
